# Generated by Django 5.1.1 on 2024-09-23 15:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('watchlist_app', '0007_rename_watchlist_review_watchlist'),
    ]

    operations = [
        migrations.RenameField(
            model_name='review',
            old_name='watchList',
            new_name='watchlist',
        ),
    ]
